### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by dbugit**
Sabre/Dav 2.0 not compatible anymore with owncloud.

### CODE REVIEW

**Comment by RETCombine** [comment]
Would it be possible to have this pull request merged ? I'm having issues with the dependency on version 2.0 of sabre/dav as I'm already using version 3.0 of sabre/event in my project.

**Comment by frankdejonge** [comment]
The tests currently fail, this can be merged when those are fixed. If you need help, let me know I'll see where I can assist.

**Comment by dbugit** [comment]
Although I also agree that this should be updated, Ive managed to solve all issues related with it and had been working with Sabre/Dav 2.0 to access Owncloud.
So, if you need help, please let me know.

**Comment by frankdejonge** [comment]
@dbugit there's already another PR which fixes this and the tests. It's merged and tagged :)

**Pull request closed without merging**
